[package]
name = "LearningRust"
version = "0.1.0"
edition = "2021"
default-run = "Target/Binary/Lib.rs.bin"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
