name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    
    - uses: lukka/get-cmake@v3.26.0

    - name: Configure CMake
      run: mkdir build && cmake -GNinja -S . -B build -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++"

    - name: Build
      run: cmake --build build -v

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: python ../gtest_run.py

